language: ruby
rvm:
- 2.3.3
addons:
  apt:
    packages:
    - lftp
script:
- bash _scripts/build.sh
after_success:
- bash _scripts/deploy.sh
env:
  global:
  - secure: MfikeOI+JnZ1vi/GGGo/iMz48w2S+l17EJmBPTFkZdn3Mu8RUD159wskYWHyyuhmWxDYsoeyiPLscuuK49ybR4IkqyJwVu0vk2H5+EeGjBXpsEDdx+RliuJ5HxOiQl2fbzz9Fih8wd7tkJOcIJSYUwlviogDcBocI3QNxCAiUB09nwz9WacH3EQypZDsC/46JRwok7GkamYEs4XKIzrrxVfLixTyEWH5PmvBVgGUQAxk5qR/IfNOKZuFKKEpOX5U/Ogvb7ZmiS5Fe/+LT7q3xw5Exs3hMd7m3JtFi9ePS5ppBUQpLGu0TdksXWzUMVh6qhjSdL5fi2mO+sY76uM02S0XoSxfRGodbdx3ATpicFOz7fLTnsJ01GNCncaF5mrYjj/rhbdbNTjtDWmQ1onWE+qYl627NVsE0UnMsgHmz6DQoX4wrXsi3L4262RG016BgN/YtS64qUbIx5skdr7kn8xkfgc1HTcljorbjl9t5zIP8BMmYHkNucieBk+DwchxWYbcVNxj2a2X2BGI8g9fNjiEmFx8VIQYILTOnT+PAbH+RDcEcBM52dJWgoMJDgKoqWN4Fz6Oo/ddm8gleJU6sx5L+gYoKIEg6HqXGLOEeWkyuul7udwBG3I4hX68PSjTZZmSMck0gjVUMDqL2rxNv5DmZrJRn5L23jM5Sj4bcvM=
  - secure: Ydr5hVoS+mO2AAL0PqF0yjBJrGepIdyeoncTsaLLLlNFN6WL8TgsShzOQUTb92FrDIRVVED9SycwX7yjMazJmfU98Gs9DmLCCChQ37SkUiLyXRjcD2c5QB7SsW60JhvVnFO8JdfFaJXBnRMC/tXy9YHtrRNxYSATnx841aZ/zoNEqoV7ep6WdFZyzcVahXOY2GQ+nfhxgtekTQePO1dc4eLVgHa7hmw7T5ROuwk4uBXyvV64z7FC11J8fuvq6Lo5pEwO4/CQ/jvOQ8uVx4ta3N3I3kpOaQELGX1N902JStGiLVsHvU5C3a8LLrb6/NrHss5+JNW0ypYOSABpFbLt9mYfnAVqLwAzHOnu6meJ8KHDRE8Fm5UwpRYAwn9dldch8DNFBaIgKaRPNBk0nR7AKPI+FeB7p6ALUFfnHwqfNv6gvbKorVpK7vWbc59bVmlp/apVvO1LDE8mD/1QpSrqJG6x3h4KQSyepIcIZkj+oESt3cARrvLNHyQEDcQ0eVKfv2T/lZ3mRVb/udEZ8gWp2+oR+AMkLtybeLzDkVwZp+40AlikSk4SRhqYgmFxAnlAqrjc04UoYG76vNnghuIPD5n3rLZarlbx3uh9hAvludQKMeCJhw+YIQDqyCFJYKbaK387i7gV1zBUcc0XADoG1gT2udcQkGMloZmLZBLsI4w=
