language: ruby
rvm:
- 2.3.3
addons:
  apt:
    packages:
    - lftp
script:
- bash _scripts/build.sh
after_success:
- bash _scripts/deploy.sh
env:
  global:
  - secure: oC05tz2tMCxHLc2653ciuOMHNUQNvvq4RcbDFK7xT6x9KdDOijbXYD6v0XfbzzPM//MceRhACIp0xZfnkCJNHVPQi0Av0f1tD4X/eCZX/k6RoNamRAFDQmtMaVhbVindycn4grF0bMpfIW6CYKWjG7So+hD7iyuL8xADpi2dt8RDKFrJ17Xl8vGs95bpMa3VHB3SY21C+21r0j4uXnb0JmEwENjZyFg0rsmluQC72GE2QwSVMmF0TINuc4YET5z+3XoV/LABnVlZz1rpOSSKoqiv1HOpIuyqRtehK1u2AW0IDXc7mIoI2VmM6Huuynnlk42A4/PaYSmcM23UI9kZZkf5WByreNW9n4cmh6jR6VtCSujpiVqILwI4SnLPcBOxWpqNhnXUM4NoH/4L23PJwE6X9ybUA9s8BAuUAVCWa0+AdodkPpGkEtHNJ8IYYflTpUC1NDa77NoDKMWf/kTcCBhiTatw1T8mDR3EJq+4TEGdQwaufGy3J8C9z/2WuldMAkFhiRTI5DoHBsdefchrQTgxZuMXfgaIni8qUaC+5YqKtHNb1ay+HXB+vQyIHBfGWqjjGUE+WCAFdv7DrKSxAT/5Q9dy+FvjuszKtlm/8ay2g8q8on+jjhvnloFAxMrOgsjnK1yaj9hN2XquCE1Nht290vP7o2KVK1gc+ePGQn0=
  - secure: AgxddF+qeJAAyrJkXETYqDauGEHx+hJrHlZQsZAGdZPy1TbCmoA7rn0X1+gUrVUeYgI8E3U2lCwYlD0ApZlEKTV5PqdWqR8oH4+k+KSEw/uBxj0RbLlHzwRhLBMu3dDnRdyDLJZeBlaDPGRMe0rqMRBR0DDvoVRcEgoMNw6XExz1dutazVgBKqJ6sXoAuVnWDLqXe836hOGTlNhqez8f7kgvwGF4vy2cR1jCLlIfwpqH30JnzDK2hw5D6BpYa9GY771nM+CCLjD/6iiLFz0UARDpxl/LI2HDHuQgwDrT//VaUc45seMLsAgMJ4YJMmaHLqvOGP7rgkHr9CLgtX6l+8g+MPAhFrGPmhVjl//g3FzckfHocsYXArSbHCKY5y3oN/p5dGOHyKcQ7ZZm4SGysJg1OTWSL0suOx6EDSZ8Rm1sKvxaz5E9LJhnlhf5XFtmK9ezyAllwf+irVHPEXJcyrBYoipwACfsClyRdtJ597LMnN/yVJ9AmsJVlfJZu1fFyiyGQwdhk357P8h39t1lySDGvJXKi6rF6CLA1E0mTmrXd9NpG0zq3LT+Ci4xq8FpsS+jnRW8ZacUU6ob5VFb+Y/y2aNg+9v7gmr1MZLAnrWJW4Ia2vsC+fflyfZgLpErjk6BgFXicT7RSqeXEF53RCLoTuwd/5axOIAWQMGjQWs=
