language: ruby
rvm:
- 2.3.3
addons:
  apt:
    packages:
    - lftp
script:
- bash _scripts/build.sh
after_success:
- bash _scripts/deploy.sh
env:
  global:
  - secure: Yi4sPiEIncLbOxZnkxaLCZrCckuTo/wjxRqm//JYT7QmzEIKHpgyWbuVhistZEkEHfcjRBlB+ONnci/nv+5BpME/2R44q4OsAjapKX7OjeZ9YzV6RLRurmvQXsLrgygeD8yZqjDXYK78CZ5YbqInKt+Y73AeMJczl28KLL5EctGLxdwK47I1Pq98wzwwNWOKAkfphASKNPn2CUV+daAZW9AdCC7799o6v//VnvJjyhtzGfbUOWCcxsiU23njIfdjDkZ9z+c8HSmilg/5lNnKxE+ZvbO4beQHTOOpHLqGJMcEdvDxlGKKBY/4L/beHrg1m8muoC1PNipzb/JF99EeH5M2j6WX6+5WLfcf2YCpYCcHSygcn2gBhgKYDothf7lT0l5Os20KWOiw1jXttOnpA3VIChyBCIv1oopb4BezwMGOQHbFKhSXbt3/M8JQ3n8GKmGs83QxWhp3gqIo0iZpuberTVtTZ3Zpf9qy0LG0QSC4Kjsn/4rFLzQY8rsU4BVBSfiXPubP4UorwYbOgHDCDw12pZcuAROKt3U+VwpWpjVOPnPJdFT+B2o03kP0dorQQNFDanlGbQZO/T/bKWdB95fro5dPHwwWfFuIeohR506DVTDJsweoDf4Q5DS0KMIlIbA57NjwWg6b3Cpbgb86LCdB8XLQ0aWmTkW1ZZRtf8E=
  - secure: NkcDPZJe7wp9dNB0wvv0JGml8QkxJPjb/R2uZHPideyA1A6lLEJqOBf8sY6iZrBp/+S/shV+Vrh77uAnrTnHwCXmiO9x7zc8xhnAADvpjcDg6ezwbfC2b5B2eDxxLI4wdoPweDrsQ+PfGTN4gLKU6E01SqjDauzi/hrsCCQjDuOLwlwsgj9ad4uXBITZ8Q0uHQKtaurDVi4J1iAVXtoGU7rXIfqVKncSC4POhuH93DHGXeaUcGjsPJ9aUW4LNSP+el6zMxcSOye3ElXjKoGnSFMX9HG1/GCsk4ZfT7+XxlbmBeiKkhAq0m+MQqb7ezq4JOuiC6Gd6a6KkAfSVwJ66ROGq6stQqtooAbWrR+hxgAiuYhfPts8t6rQEaZpeCSLJWAFsfxgHMpRxU+6U7lxse66/34NBEFUbbjIr6cz7vBDY8dGP5z7Eq7JhSdexLWL0N/R5drsojsxDuBgC6Togax/Fx/sPAzdkTg2OysPeQngWlmH3pHsEbZQKEniVrcEByHAZMOdorFJMqgYVBYatSwhHsWG20pNAMP6snkRAlIagq9NKATAc8B0h1lyq4Qetub6Yjq7INPxItCnr6//rwcnFALWdHU3efIU561On3t93R/NlCgxPPA52E7X1ljQKvg3hHxvHSnXFgfji2FEODGfB3vUvbg8L+jpDxEoIxk=
