language: ruby
rvm:
- 2.3.3
addons:
  apt:
    packages:
    - lftp
script:
- bash _scripts/build.sh
after_success:
- bash _scripts/deploy.sh
env:
  global:
  - secure: Uv3/tK5jepT5JxKCHuTNuDIIf+iO9Y4H0YujXD60YFGPwd0TXMLd73oVp48OhmCt2QqHTHZ8FFU6YUTbCrpBL4XhoEkeTb088L3ZMy+WZf7hD0yiTQaSTDFwktvXqfBZHDDJ7AX2OdwT1AS7T3y6DeRHoN2+YmF71SLuzN8x/pSBL4FXXv87xrlWQlBEW0WyQlTz/NOemKDa1U4/eXLmy1d+J7rxF4Ga4ulOveoneCRi3/aD4RNB7AA8PGufFV2HRaV0EoBAWVyTlp/UT6rUTzgLqP63XjSXjWEMwhSHxZFEZlhCW3mA8D9LxxR2AULANMVWoT2ftSsSjoQG70k5CZVanmaEBZP9mP479a3xKT7gioNUsdwUGSHxrRjHEGs6cEHZbLrjX8TL9MpgORYd+ecsb5Yc4ccuoqWNorYi3d5BQqj/l7tNNLrLf3JpZ0XNwoFCRat2BXbyd+CGgGYrZNgaZyEWec+NSmjoqBllxKBz5098iNEqsG2nBVupcGSQY+383QZVOnGBQqnkhv7flErBRjWuMN6rQqwShSRtoAFRzl2P6VbgOlz8iZvpyyjEXTS5CYkGYMzErvOOnctLTap1MN35B89UgYRNNJx/U1WlPseUiVvKnk+02S8N4SiTIRsJjYU4BFk9hB+Kr9fw+Oce5HG7pprwwjN38VMqWhw=
  - secure: jwh600onGo3vWB59oZhy5tSJFo5i6gnXJqjvK2ynuMu21hZod8iFZdIUQzG3dIdJgrxgX+0/sAyOF3W4l2RyW2nAg8VHGN1prRjGlKFUfiYLXgjBeh29UOlJivA03fkHz950gym5Daqm+rHNJNY0aSU/RUTZqU7Rt5zBsvC7VOQZtsniWuBADtmsbQFJK6PCEHo3zct/UDCRudXGZzXO/Qe17k9PHSU0qjdeT9T75p7/bZj/AfBYt3/K9xuDNWs8wYzaYuiFSEzvvQn+VteBDt37/qmOQonaK2uslF3KrPPe3sVvz1/BJlUUXEgJmJMqph79M7KdIhl1mAU7z6sQSBhlTJvNpA/NUvDj3uCW7C/ZljUYM7bOwRoq01I9+Fsrh/IHo+hEqXqcylwwAnsRCYTU88Vv+oFwvDTAVVIa5tlOkVIFjIGJjtiyfydxbhDzGZig6GMy8EB5zG5yVz/uDjncHVczvz0qd0EzfAbymO6Anm+aLpxtygzvc1Hj+eroSYhwmBAXkNnPUjkYD170+cXmK28N3JQmJ9/y4b8g9GcKx8zxhVnNzRZmtSlGnwzRisYj2OQbpTpVsI1HS0Is+ZXrgysGMHEWyhsctUsVmGVjKQAiP/d9lGN3WGML414UOKNZj8iOXoMhmZewaEAS9Cvg8a+0loxHdJgvOj8P4SQ=
