# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: IEEE UP Student Branch
email: nuieee@fe.up.pt
description: > # this means to ignore newlines until "baseurl:"
  IEEE UP SB is a Student Branch (SB) that is composed by University of Porto (UP) students and members of IEEE, whom have the passion of sharing knowledge and make activities that grant to our student community and also to technological advance.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nuieee.fe.up.pt" # the base hostname & protocol for your site, e.g. http://example.com
logo: ieee.png
facebook: ieeeupsb
instagram:  ieeeupsb
flickr:  nuieee
excerpt_separator: <!--more-->
# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
